/** @type {import('tailwindcss').Config} */
export default {
  darkMode: 'class',
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        "on-error": "#690005",
        "on-error-container": "#ffdad6",
        "inverse-primary": "#6d4ca6",
        "surface-tint": "#d4bbff",
        "tertiary-fixed-dim": "#bdc7dc",
        "inverse-on-surface": "#2a303d",
        "tertiary": "#bdc7dc",
        "on-primary-fixed": "#270058",
        "surface-container-low": "#161c27",
        "on-secondary-fixed-variant": "#514700",
        "error-container": "#93000a",
        "outline": "#958e9c",
        "surface-container": "#1a202c",
        "on-primary-fixed-variant": "#55338d",
        "secondary-container": "#a3910d",
        "on-secondary": "#383000",
        "on-tertiary": "#273141",
        "on-tertiary-fixed": "#121c2c",
        "primary-fixed-dim": "#d4bbff",
        "on-secondary-fixed": "#201c00",
        "surface-container-high": "#242a36",
        "surface-variant": "#2f3542",
        "on-secondary-container": "#302a00",
        "primary-fixed": "#ebdcff",
        "error": "#ffb4ab",
        "on-tertiary-fixed-variant": "#3d4759",
        "surface-container-lowest": "#080e1a",
        "tertiary-fixed": "#d9e3f9",
        "surface": "#0d131f",
        "secondary-fixed": "#fae361",
        "secondary-fixed-dim": "#dcc748",
        "inverse-surface": "#dde2f3",
        "on-surface-variant": "#ccc3d2",
        "primary": "#d4bbff",
        "on-surface": "#dde2f3",
        "background": "#0d131f",
        "surface-dim": "#0d131f",
        "secondary": "#dcc748",
        "on-primary-container": "#492680",
        "tertiary-container": "#9ca6bb",
        "on-tertiary-container": "#323c4d",
        "surface-container-highest": "#2f3542",
        "surface-bright": "#333946",
        "on-background": "#dde2f3",
        "primary-container": "#b794f4",
        "outline-variant": "#4a4551",
        "on-primary": "#3e1975",
        "terminal-dot-red": "#ff5f56",
        "terminal-dot-yellow": "#ffbd2e",
        "terminal-dot-green": "#27c93f"
      },
      borderRadius: {
        "DEFAULT": "0.125rem",
        "lg": "0.25rem",
        "xl": "0.5rem",
        "full": "0.75rem"
      },
      spacing: {
        "max_width": "1200px",
        "gutter": "24px",
        "md": "16px",
        "xl": "48px",
        "sm": "8px",
        "xs": "4px",
        "lg": "24px",
        "unit": "4px"
      },
      fontSize: {
        "h1": ["3.5rem", { lineHeight: "1.2", letterSpacing: "-0.02em" }],
        "body-lg": ["1.125rem", { lineHeight: "1.6" }],
        "code-md": ["0.875rem", { lineHeight: "1.5" }],
        "code-sm": ["0.75rem", { lineHeight: "1.5" }],
        "terminal-header": ["0.75rem", { letterSpacing: "0.05em" }]
      },
      fontFamily: {
        "body-lg": ["Geist", "sans-serif"],
        "code-sm": ["JetBrains Mono", "monospace"],
        "code-md": ["JetBrains Mono", "monospace"],
        "label-caps": ["JetBrains Mono", "monospace"],
        "h1": ["Space Grotesk", "sans-serif"],
        "body-md": ["Geist", "sans-serif"],
        "h2": ["Space Grotesk", "sans-serif"],
        "terminal-header": ["JetBrains Mono", "monospace"]
      }
    },
  },
  plugins: [],
};
